### ISSUE TITLE
配置文件的加载不友好

### ISSUE THREAD

**Issue by kvchoi** [aofeng/common4j#1]
看了下DomUtil是使用getResourceAsStream读取文件，这就要求配置文件与类同一目录下。这次play框架中使用不方便，因为conf跟在另外一个目录了。

**Comment by aofeng** [comment]
科普一下：CLASSPATH是以冒号":"分隔的多个目录或文件，应用在CLASSPATH中的目录和文件加载class和文件等资源。

getResourceAsStream在CLASSPATH的所有路径中查找指定的文件并进行加载，不需要与类同一目录。

类所在的目录默认位于应用的CLASSPATH中，所以放在类目录中的文件可以通过getResourceAsStream方法进行加载。
